### ISSUE TITLE
Exception while running ./gradlew :app:assembleDebug

### ISSUE THREAD

**Issue by akabravo97** [menny/bazel-leaf#2]
I am getting java.net.SocketTimeoutException while running the above command. Here's my terminal log

`71 actionable tasks: 71 executed

Publishing build scan...

A network error occurred.

If you require assistance with this problem, please report it to your Gradle Enterprise administrator and include the following information via copy/paste.

----------
Gradle version: 4.5.1
Plugin version: 1.11
Request URL: https://real-gradle.spotify.net/in/4.5.1/1.11
Request ID: 1a7b9d9c-0a8f-4b78-9036-b4f64b7a5b01
Exception: java.net.SocketTimeoutException: connect timed out
----------`

**Comment by BryanRansil** [comment]
From what I can tell, this is because it's trying to publish debug information to the main spotify repo (that request URL). I've been able to delete the buildScan function and it looks like the tasks complete as normal. Though I'm dealing with my own build problem so take that with a grain of salt ;)
